version: "3.4"
services:

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=2500'
